### ISSUE TITLE
Mapping of measurementTypeID, measurementValueID, measurementUnitID

### ISSUE THREAD

**Issue by peterdesmet** [inbo/esas2obis#10]
- [x] All TBD in this list should be resolved.
- [x] All `untested` in this list should be resolved (or at least checked) -> Moved to other issue

### measurementType

Lowercase, space separated description, e.g. `platform class`.

### measurementTypeID

Link to http://vocab.nerc.ac.uk/collection/P01/current/ or specific recommended vocab (http://vocab.nerc.ac.uk/collection/S11/current/) if a good applicable definition can be found there.

Otherwise, link to ICES vocab that was used (e.g. https://vocab.ices.dk/services/rdf/collection/PlatformSide). Note that these links don't provide a definition, but their URL is meaningful.

Leave empty if no good definition exists out there.

### measurementValue

Give the most meaningful value, so it can be understood out of context. E.g. the full description of a term:

> Binoculars used extensively for scanning ahead and to the side, naked eye used for close observations (e.g. for cetacean monitoring)

Or the translation of a value to more meaningful values (NE -> 45°).

Note that very often, the original code (e.g. `NE`) will be part of the URL in `measurementValueID` (e.g. `https://vocab.ices.dk/services/rdf/collection/TravelDirection/NE`), so that code is not lost.

### measurementValueID

Link to recommended vocab term (e.g. http://vocab.nerc.ac.uk/collection/S11/current/S1116/) if a good match can be found.

Otherwise, link to the term in the ICES vocab that was used (e.g. https://vocab.ices.dk/services/rdf/collection/LifeStage/3)

Leave empty if no controlled vocab was used.

### measurementUnit

Lowercase unit, e.g. `degrees`, `km2`, `Beaufort `.

Leave empty for terms where a unit does not apply.

### measurementUnitID

Look for relevant unit in P06, e.g. http://vocab.nerc.ac.uk/collection/P06/current/SQKM/

If the measurement is dimensionless (e.g. a count, beaufort), use https://vocab.nerc.ac.uk/collection/P06/current/UUUU/

Otherwise, set to not applicable: https://vocab.nerc.ac.uk/collection/P06/current/XXXX/

---

## sample: PlatformCode: ok

- measurementTypeID: http://vocab.nerc.ac.uk/collection/C17/current/
- measurementValueID: http://vocab.nerc.ac.uk/collection/C17/current/11BE
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## sample: PlatformClass: ok

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/Platform%20Class _Not in P01, not http://vocab.nerc.ac.uk/collection/R23/current/_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/Platform%20Class/30
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## sample: PlatformSide: ok

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/PlatformSide _Not in P01 or other vocabs_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/PlatformSide/left
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## sample: PlatformHeight: untested (not in sample data)

- measurementTypeID: none _Not http://vocab.nerc.ac.uk/collection/P01/current/AHSLZZ01/ which is the height above sea level of the observation (not observer)_
- measurementValueID: none
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/ULAA/

## sample: TransectWidth: ok

- measurementTypeID: none _Not https://vocab.nerc.ac.uk/collection/Q01/current/Q0100013/ which is the width of a device_
- measurementValueID: none
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/ULAA/

## sample: SamplingMethod: ok

- measurementTypeID: http://vocab.nerc.ac.uk/collection/P01/current/SAMPPROT/ _Decided not to choose https://vocab.nerc.ac.uk/collection/Q01/current/Q0100003/, see comment below_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/BD_CountMethod/1
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## sample: PrimarySampling: ok

- measurementTypeID: none _Not in P01 or ESAS_
- measurementValueID: none _TRUE/FALSE_
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## sample: TargetTaxa: ok

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/TargetTaxa _Not in P01_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/TargetTaxa/1
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## sample: DistanceBins: ok

- measurementTypeID: none _Not in P01 or ESAS_
- measurementValueID: none
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/ _Arguably meters, since it is a list of meter intervals: `0|50|100|200|300`, but it's more a fact than a measurement_

## sample: UseOfBinoculars: ok

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/UseOfBinoculars _Not in P01_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/UseOfBinoculars/3
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## sample: NumberOfObservers: ok

- measurementTypeID: none _Not in P01 or ESAS, pretty clear_
- measurementValueID: none
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/UUUU/

---

## pos: Distance: ok

- measurementTypeID: http://vocab.nerc.ac.uk/collection/P01/current/DISTPHMS/ _See https://github.com/inbo/esas2obis/issues/18_
- measurementValueID: none
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/ULKM/

## pos: Area: see https://github.com/inbo/esas2obis/issues/19

- measurementTypeID: _?
- measurementValueID: none
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/SQKM/

## pos: WindForce: ok

- measurementTypeID: http://vocab.nerc.ac.uk/collection/P01/current/WMOCWFBF/ _Speed of wind {wind speed} in the atmosphere by visual estimation and conversion to Beaufort scale. Same as 	http://vocab.nerc.ac.uk/collection/P09/current/WBFO/_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/Beaufort/2 _No beaufort scale at BODC_
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/UUUU/ _Indicated as such in WMOCWFBF_

## pos: Visibility: see https://github.com/inbo/esas2obis/issues/20

- measurementTypeID: http://vocab.nerc.ac.uk/collection/S06/current/S0600244/ _Not in P01_, but a relevant S06 term #20
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/Visibility/1
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/ULKM/ _Categories like A are translated to ranges `0-1`_

## pos: Glare: ok

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/Glare _Not in P01_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/Glare/medium
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## pos: SunAngle: untested (not in sample data)

- measurementTypeID: none _Few terms related to sun in P01, but not sun angle. Not in ESAS either._
- measurementValueID: none
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/UAAA/

## pos: CloudCover: untested (not in sample data)

- measurementTypeID: http://vocab.nerc.ac.uk/collection/P02/current/CHEX/ _See https://github.com/inbo/esas2obis/issues/21_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/CloudCover/2
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/UUUU/ _Cf. beaufort, I would go for dimensionless rather than not applicable for octas_

## pos: Precipitation: ok

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/Precipitation _Not in P01_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/Precipitation/R
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## pos: IceCover: ok

- measurementTypeID: http://vocab.nerc.ac.uk/collection/P07/current/CFSN0424/ _See https://github.com/inbo/esas2obis/issues/22_
- measurementValueID: none
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/UPCT/

## pos: ObservationConditions: untested (not in sample data)

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/Sightability _Not in P01_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/Sightability/G
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

---

## obs: GroupID: ok

- measurementTypeID: none _Not in P01 or ESAS, decided not to express as events: see #12_
- measurementValueID: none
- measurementUnitID: none

## obs: Transect: ok

- measurementTypeID: none _Not in P01 or ESAS_
- measurementValueID: none _TRUE/FALSE_
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## obs: Count: ok

- measurementTypeID: http://vocab.nerc.ac.uk/collection/P01/current/OCOUNT01/
- measurementValueID: none
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/UUUU/

## obs: ObservationDistance: ok

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/ObservationDistance _Not in P01 (although there are other terms relating to distance)
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/ObservationDistance/B
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/ULAA/ _Except for F and W, which are not expressed in m_

## obs: LifeStage: ok

- measurementTypeID: http://vocab.nerc.ac.uk/collection/S11/current/
- measurementValueID:
  - adult: http://vocab.nerc.ac.uk/collection/S11/current/S1116/
  - immature: http://vocab.nerc.ac.uk/collection/S11/current/S1171/
  - calendar years: https://vocab.ices.dk/services/rdf/collection/LifeStage/3 etc.
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## obs: Moult: ok

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/Moult _Not in P01_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/Moult/Y
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## obs: Plumage: ok

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/Plumage _Not in P01_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/Plumage/C
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## obs: Sex: ok

- measurementTypeID: http://vocab.nerc.ac.uk/collection/S10/current/
- measurementValueID:
  - F: http://vocab.nerc.ac.uk/collection/S10/current/S102/
  - M: http://vocab.nerc.ac.uk/collection/S10/current/S103/
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## obs: TravelDirection: ok

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/TravelDirection _Not in P01, all direction terms relate to e.g. platform, wind or waves_
- measurementValueID:
  - https://vocab.ices.dk/services/rdf/collection/TravelDirection/NE for cardinal directions, which are expressed as degrees (45) in value
  - NULL: for raw degree values
- measurementUnitID: https://vocab.nerc.ac.uk/collection/P06/current/UAAA/ _All values translated to degrees_

## obs: Prey: ok

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/PreyType _Not in P01_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/PreyType/33
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## obs: Association: ok

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/Association _Not in P01_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/Association/110
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

## obs: Behaviour: ok

- measurementTypeID: https://vocab.ices.dk/services/rdf/collection/Behaviour _Not in P01_
- measurementValueID: https://vocab.ices.dk/services/rdf/collection/Behaviour/113
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/XXXX/

**Comment by peterdesmet** [comment]
Guidelines for `measurementTypeID`, in order:

1. Try to use one from http://vocab.nerc.ac.uk/collection/P01 (using http://vocab.nerc.ac.uk/search_nvs/)
2. If not, set to ICES 
3. If not, leave empty

Guidelines for `measurementValueID`:

1. Try to use values from http://vocab.nerc.ac.uk/collection/P01/current/LSTAGE01/ or other relevant vocab
2. If not, set to ICES
3. If not, leave empty

Guidelines for `measurementUnitID`:

1. Set to http://vocab.nerc.ac.uk/collection/P06/current/ULAA or similar
2. If fact, use https://vocab.nerc.ac.uk/collection/P06/current/XXXX/
3. If unit not found in P06, leave empty

**Comment by peterdesmet** [comment]
@rubenpp7 should I use http://vocab.nerc.ac.uk/collection/P01/current/SAMPPROT/ or the OBIS specific https://vocab.nerc.ac.uk/collection/Q01/current/Q0100003/ for sampling protocol?

**Comment by peterdesmet** [comment]
@rubenpp7, how should ranges be expressed? `5-10` and `>10`?

**Comment by rubenpp7** [comment]
@peterdesmet I would use http://vocab.nerc.ac.uk/collection/P01/current/SAMPPROT/ for sampling protocol

ranges can be expressed both as 5-10 as >10 indeed
