### ISSUE TITLE
Should groupID be an event?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/esas2obis#12]

**Comment by peterdesmet** [comment]
@nicolasvanermen, can group identifiers extend positions? I.e. is it possible that a group identifier `A` is used over multiple positions or is it always restricted to that position?

**Comment by nicolasvanermen** [comment]
Yes groudID can extend over multiple positions!

**Comment by peterdesmet** [comment]
Ok, in that case we should definitely not consider it a child event of positions, but its own property
