### ISSUE TITLE
P01 term for Distance

### ISSUE THREAD

**Issue by peterdesmet** [inbo/esas2obis#18]
Distance is defined as:

> Distance travelled during the observation bin in km. Can only remain empty if Area is used.

There are two existing terms that come close:

## Distance travelled

- http://vocab.nerc.ac.uk/collection/P01/current/DSRNCV01/
- The along-track distance the platform has travelled **since the start of the current cruise or mission**
- Related to broader "All parameters relating to horizontal platform travel, including distance run"

## Distance (along transect)
- http://vocab.nerc.ac.uk/collection/P01/current/DISTPHMS/
- No definition.
- Related to broader "All forms of horizontal spatial coordinates such as lat/lon and grid references".

The first one is great, because it relates to the platform movement. But ours is within the distance bin, not since the start of the cruise. @rubenpp7 @nicolasvanermen which one should I pick, if any?

**Comment by nicolasvanermen** [comment]
Any SAS cruise is indeed divided in many observation bins of 1 to 10 minutes so the first definition does not cover the load. "Distance (along transect)" without further specification seems okay to me.
