### ISSUE TITLE
P01 term for visibility

### ISSUE THREAD

**Issue by peterdesmet** [inbo/esas2obis#20]
Visibility is defined as:

> Visibility in kilometer, uses the Visibility vocabulary. It can use numbers or categories, e.g. `A Poor (< 1 km)` which can be translated to km.

There some existing terms that come close:

## Horizontal visibility in the atmosphere by scattering photometer

- http://vocab.nerc.ac.uk/collection/P01/current/VISHOR01/
- Maximum horizontal distance through the atmosphere at which an object can be seen and identified by the unaided eye estimated from the extinction coefficient measured by a scattering photometer.
- Broader: Horizontal visibility

## Horizontal visibility

- http://vocab.nerc.ac.uk/collection/S06/current/S0600244/
- Maximum distance at which an observer can see and identify an object lying close to the horizontal plane on which he or she is standing. (source: AMS glossary, 20200219)

## Horizontal visibility (WMO code) in the atmosphere by visual estimation and conversion to WMO code using table 4300

- http://vocab.nerc.ac.uk/collection/P01/current/WMOCHVXX/
- No definition
- Broader: Horizontal visibility (WMO code) (these codes are integers) and "visual estimation"

Ours is also a "visual estimation", but we don't use WMO codes, so that one is not applicable I think. The first one is too narrow, because it assumes the use of a photometer. The second sounds fine?

**Comment by peterdesmet** [comment]
@nicolasvanermen, I'm trying to match visibility as defined by ESAS with a standard (already existing) definition. Do you agree that the second definition above is the closest match with what we mean with visibility in ESAS?

**Comment by nicolasvanermen** [comment]
Yes, definitely "horizontal visibility"

**Comment by peterdesmet** [comment]
@rubenpp7 @pieterprovoost the OBIS manual recommends to use P01 or Q01 vocabularies for `measurementTypeID`: https://manual.obis.org/data_format.html#measurementtypeid

Is it ok to use a term from the `S06` vocabulary (BODC parameter semantic model parameter entity names) if there is a good match (in our case http://vocab.nerc.ac.uk/collection/S06/current/S0600244/)?

**Comment by JoBeja** [comment]
Hi Peter, 

I got forwarded this question by Pieter Provoost, through the OBIS slack channel. I thought Pieter would have replied to it here. 
You can't use an S06 as a measurementTypeID, S06 defines the properties that will be included in the creation of a P01, like a building block to P01. See the table on the readme file in https://github.com/nvs-vocabs/P01 (scroll to the end). 
Your options are to either leave the measurementTypeID null or request a new P01 if you can't find one in P01 that exactly fits your measurements.
Hope this helps.

**Comment by peterdesmet** [comment]
Thanks! I requested a new term in https://github.com/nvs-vocabs/P01/issues/178

**Comment by peterdesmet** [comment]
New vocab terms are now available and the data are mapped as such:

measurementType | measurementTypeID | measurementValue | measurementValueID | measurementUnit | measurementUnitID
--- | --- | --- | --- | --- | ---
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR04/ | A | https://vocab.ices.dk/services/rdf/collection/Visibility/A |  | 
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR04/ | B | https://vocab.ices.dk/services/rdf/collection/Visibility/B |  | 
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR04/ | C | https://vocab.ices.dk/services/rdf/collection/Visibility/C |  | 
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR04/ | D | https://vocab.ices.dk/services/rdf/collection/Visibility/D |  | 
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 0.1 | https://vocab.ices.dk/services/rdf/collection/Visibility/0.1 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 0.2 | https://vocab.ices.dk/services/rdf/collection/Visibility/0.2 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 0.3 | https://vocab.ices.dk/services/rdf/collection/Visibility/0.3 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 0.4 | https://vocab.ices.dk/services/rdf/collection/Visibility/0.4 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 0.5 | https://vocab.ices.dk/services/rdf/collection/Visibility/0.5 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 0.6 | https://vocab.ices.dk/services/rdf/collection/Visibility/0.6 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 0.7 | https://vocab.ices.dk/services/rdf/collection/Visibility/0.7 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 0.8 | https://vocab.ices.dk/services/rdf/collection/Visibility/0.8 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 1 | https://vocab.ices.dk/services/rdf/collection/Visibility/1 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 1.5 | https://vocab.ices.dk/services/rdf/collection/Visibility/1.5 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 10 | https://vocab.ices.dk/services/rdf/collection/Visibility/10 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 2 | https://vocab.ices.dk/services/rdf/collection/Visibility/2 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 2.5 | https://vocab.ices.dk/services/rdf/collection/Visibility/2.5 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 3 | https://vocab.ices.dk/services/rdf/collection/Visibility/3 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 3.5 | https://vocab.ices.dk/services/rdf/collection/Visibility/3.5 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 4 | https://vocab.ices.dk/services/rdf/collection/Visibility/4 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 5 | https://vocab.ices.dk/services/rdf/collection/Visibility/5 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 6 | https://vocab.ices.dk/services/rdf/collection/Visibility/6 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 7 | https://vocab.ices.dk/services/rdf/collection/Visibility/7 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 8 | https://vocab.ices.dk/services/rdf/collection/Visibility/8 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
visibility | http://vocab.nerc.ac.uk/collection/P01/current/VISHOR03/ | 9 | https://vocab.ices.dk/services/rdf/collection/Visibility/9 | km | http://vocab.nerc.ac.uk/collection/P06/current/ULKM/
