### ISSUE TITLE
P01 term for cloud cover

### ISSUE THREAD

**Issue by peterdesmet** [inbo/esas2obis#21]
Cloud cover is defined as:

> Cloud cover expressed as x/8 (octas). Uses the CloudCover vocabulary.

There some existing terms that come close:

## Cloud cover (all clouds) in the atmosphere by visual estimation and conversion to WMO code

- http://vocab.nerc.ac.uk/collection/P01/current/WMOCCCAC/
- No definition
- Broader: Cloud cover height and extent

## Cloud cover height and extent

- http://vocab.nerc.ac.uk/collection/P02/current/CHEX/
- Parameters describing the horizontal and vertical extent of cloud cover

@nicolasvanermen @rubenpp7 Since the first term specifies WMO codes (and we use octas), I think we have to go for the broader term?

**Comment by nicolasvanermen** [comment]
Unless there is a WMO scale dedicated to cloudliness and which is easily linked to octas (which I doubt) I guess we should go for a seperate vocubulary.

**Comment by peterdesmet** [comment]
> I guess we should go for a seperate vocubulary.

Why not link to the broad description in http://vocab.nerc.ac.uk/collection/P02/current/CHEX/ ?

**Comment by nicolasvanermen** [comment]
OK misunderstood this, if the broader description allows octas as a 'unit' that is fine of course.

**Comment by peterdesmet** [comment]
Thanks! I'll use that one.
