### ISSUE TITLE
Coordinates in observation.notes

### ISSUE THREAD

**Issue by peterdesmet** [inbo/esas2obis#9]
@nicolasvanermen in the observation notes I find a lot of values that look like coordinates, e.g `8.1300000000`. What is the intention of these values?

**Comment by nicolasvanermen** [comment]
No idea, maybe Eric knows, I will ask him... but does this matter?

**Comment by peterdesmet** [comment]
@ericstienen any idea why coordinates are sometimes written in the notes of an ESAS observation? Notes include a variety of values that are often hard to interpret:

```
...
JADE RIVER
MOSSELKWEEK
TTB - C2
11.5000000000
12.2500000000
12.3500000000
270° 150M
270° 250M
...
```

**Comment by EricStienen** [comment]
Seems relevant info on place where a bird was seen (e.g. cormorant in association with mosselkweek) or tern sitting on buoy/turbine named TTB-C2. 

270° 150m gives the position of a vessel or a seamammal relative to the position of the observation vessel. Used very often and relevant!

**Comment by EricStienen** [comment]
looks like time stamps. To what euring code do notes like 11.500000 belong to?

**Comment by EricStienen** [comment]
does not immedaitely ring a bell. I have to see the entire line including date, time and behaviour. Maybe that will help.

**Comment by peterdesmet** [comment]
Here's all the data for those records: [notes.csv](https://github.com/inbo/esas2obis/files/8317202/notes.csv)

**Comment by EricStienen** [comment]
indeed these are time stamps. Such was done in the early days when bouts for counting lasted 10 minutes. Rather imprecise if you wanted to know if a bird was positioned above a sandbank or not. In the orginal notes these time stamps look like 10:10 but somwhre in the process that has become 10.10000000. Do not ask me why.
